server:
  port: 9999
spring:
  application:
    name: authorization-server
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      database: mmdb
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost
